# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-07-07 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Profile', models.CharField(choices=[(b'Hr', b'SALES'), (b'MANAGER', b'MANAGER'), (b'ANALYST', b'ANALYST'), (b'EXTRA', b'EXTRA')], max_length=50)),
                ('Primary_category', models.CharField(choices=[(b'proto1', b'PROTO1'), (b'proto2', b'PROTO2'), (b'proto3', b'PROTO3'), (b'proto4', b'PROTO4')], max_length=50)),
                ('assessment_name', models.CharField(max_length=50)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qid', models.IntegerField()),
                ('qtype', models.CharField(max_length=50)),
                ('text_question', models.TextField(null=True)),
                ('ans_detail1', models.TextField(null=True)),
                ('ans_detail2', models.TextField(null=True)),
                ('ans_detail3', models.TextField(null=True)),
                ('ans_detail4', models.TextField(null=True)),
                ('ans_detail5', models.TextField(null=True)),
                ('ans_detail6', models.TextField(null=True)),
            ],
        ),
    ]
